java_binary(
    name = "run",
    srcs = ["JavaBinary.java"],
    main_class = "com.example.JavaBinary",
    visibility = ["//visibility:public"]
)

filegroup(
    name = "sources",
    data = glob(["**"]),
    visibility = ["//visibility:public"]
)